### ISSUE TITLE
agent dynamically generate OSS connections

### ISSUE THREAD

**Issue by goldenxinxing** [star-whale/starwhale#209]
**Current Behavior**
agent generate fixed oss connections via properties when bootstrap

**Proposed Behavior**
dynamically generated according to the connection information sent by the controller

**Solution Proposal**
dynamicallly generated

**Comment by anda-ren** [comment]
based on below points, this issue is moved to long-term roadmap
- pre-sigined url for object uploading will couple Controller and Agent tightly
- pre-sigined url is not guaranteed other than s3 protocol
- variation on object storage will cause the change on controller result showing design/ agent file downloading&uploading / task set file downloading, the size of this workload is not middle
- variation on object storage is not a strong requirment in current phase
